- src/js/pages/home/index.js
- src/templates/home.ejs
> Rocky front end

- src/js/serie/rck-prudct-dadoEstruturado.js
Update of structured data to show parameterized URL of according to SKU in "Offers"
> Update of structured data

- src/js/serie/rck-prudct-dadoEstruturado.js
Fix the Structured Data for the Google Merchant, assigning a single structured data to products page that have the parameterized url
> Fix the Structured Data for the Google Merchant

- src/js/serie/rck-prudct-dadoEstruturado.js
Making the variation appear selected if the URL is parameterized by the SKU.
Obs: It's just a fix for Merchant, so the selection is not dynamic.
> Making the variation appear selected if the URL is parameterized by

- inProduction/js/outhers/rck-brindeColection.js
fix issue when cart product returns empty json
> BUGFIX PROGRESSBAR colection brinde

- src/scss/pages/home/index.scss
- src/templates/home.ejs
Placing arrows on the home banner
>  Placing arrows on the home banner

- src/scss/pages/home/index.scss
assigning text alignment center to value proposition
> assigning text alignment center to value proposition

- src/scss/pages/home/index.scss
- src/templates/home.ejs
Adjusting the size and spacing for the value proposition
> Adjusting the size and spacing for the value proposition

- src/templates/partials/subtemplates/header.ejs
BUG:  When clicking the search icon on the mobile device, the page is scrolled to the top position.
> BUG FIX - remove autoscroll top

- inProduction/js/frn.lojapiticas.general.js
BUG: when open modal of search in the mobile, the button search closing modal in click.
> BUG FIX - Input text search

- src/templates/partials/subtemplates/head.ejs
Google Optimize script addition in head tag
>  Google Optimize script addition

- inProduction/js/frn.lojapiticas.general.js
> BUGFIX -  search smarthint input

- src/templates/partials/subtemplates/head.ejs
- src/templates/partials/subtemplates/scripts.ejs
Changing the position of Google Optimize Snippet for the scripts of footer
> Google Optimize script addition fix

- inProduction/js/outhers/rck-cls-category.js
> fix cls caregory pages

- src/templates/category.ejs
declaration of new script name of CLS fix and selection "Order By"
> declaration of new script name of CLS fix and selection "Order By"

- inProduction/js/outhers/rck-cls-category-and-order-by.js
Order By filter color adjustment selected
> Order By filter color adjustment selected

- src/scss/pages/account/index.scss
> FIX- my account UI

- inProduction/js/frn.lojapiticas.category.js
- inProduction/js/frn.lojapiticas.general.js
FIX - Product duplicate added on click in popup of category page;
FIX - Crashes  in flow of  purchase caused by sweetAlert
> BUG FIX - Product duplicated

- inProduction/js/frn.lojapiticas.category.js
- src/scss/pages/category/index.scss
Adjust [CRO] Mobile filter indicator for Category Pages (CSS and JS)
> Adjust - [CRO] Mobile filter indicator for Category Pages

- inProduction/js/frn.lojapiticas.category.js
- inProduction/js/outhers/rck-tagFreteGratis.js
- src/scss/pages/_general.scss
- src/scss/pages/category/index.scss
- src/templates/partials/subtemplates/scripts.ejs
Fix  [CRO] Mobile filter indicator for Category Pages
> Fix  [CRO] Mobile filter indicator for Category Pages

- inProduction/js/outhers/rck-tagFreteGratis.js
update to use the same progress bar value for shipping
> update to use the same progress bar value for shipping
